### ISSUE TITLE
Google Drive

### ISSUE THREAD

**Issue by Zurichcape** [Tverous/HRCenterNet#2]

**Comment by Zurichcape** [comment]
提供的Google drive 的pretrained weight 和数据集无法下载，请问能否提供别的下载方式呢，谢谢

**Comment by Tverous** [comment]
请问是指 Google Drive 的档案遗失吗 ?

或是指无法透过 Goole Drive 服务下载 ? 

因为我这边看档案都还在 Google Drive 上面，如果是指无法使用 Goole Drive 服务的话，我可以额外再提供 OneDrive 的下载方式

**Comment by Zurichcape** [comment]
> 可以使用Google  Drive看到您上传的档案，但却无法下载，我也不知道是什么问题，您方便的话就麻烦您提供一下onedrive的下载方式，十分感谢！

**Comment by Tverous** [comment]
已更新 OneDrive 下载连结在 README 中，如方便再麻烦帮我确认看看，感谢

**Comment by Zurichcape** [comment]
> OneDrive可以使用，感谢博主！！！
